"""added column new_balance to Operation model

Revision ID: 2c80d269c7e0
Revises: 8cf027e9b4e0
Create Date: 2026-05-11 23:45:08.578045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c80d269c7e0'
down_revision: Union[str, Sequence[str], None] = '8cf027e9b4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('new_balance', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'new_balance')
    # ### end Alembic commands ###
