"""Initial migration - added hashed passwords to User model

Revision ID: 3a1622990d3f
Revises: 
Create Date: 2026-05-13 23:41:31.034344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1622990d3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'new_balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('user', sa.Column('password_hash', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.alter_column('operation', 'new_balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
